#Linux only: Uncomment when using linux
# before_script:
#- export GRADLE_USER_HOME=$(pwd)/.gradle
#- chmod +x gradlew
#Linux only END: Uncomment when using linux

stages:
- build
- test

build:
  stage: build
  script:
  - cd backend
  - ./gradlew build -x test
  - ./gradlew.bat --stop

test:
    stage: test
    script:
    - cd backend
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube-check:
  stage: test
  script: 
    - cd backend
    - ./gradlew sonarqube -Dsonar.quialitygate.wait=true
