#Linux only: Uncomment when using linux
# before_script:
#- export GRADLE_USER_HOME=$(pwd)/.gradle
#- chmod +x gradlew
#Linux only END: Uncomment when using linux

stages:
- build
- test
- sonarqube-check
- deployment-dockerhub

build:
  stage: build
  script:
  - cd backend
  - ./gradlew build -x test
  - ./gradlew.bat --stop

test:
    stage: test
    script:
    - cd backend
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube-check:
  stage: sonarqube-check
  script:
    - cd backend
    - ./gradlew test jacocoTestReport sonarqube
    - ./gradlew.bat --stop

deployment-dockerhub:
  stage: deployment-dockerhub
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --no-cache -t $CI_REGISTERY_USER/individual-semester-3-vartan-dyulgeryan-davines-app:latest -f backend/Dockerfile backend
    - docker login -u $CI_REGISTERY_USER -p $DOCKER_HUB_TOKEN
    - docker push $CI_REGISTERY_USER/individual-semester-3-vartan-dyulgeryan-davines-app:latest