version: '3' # optional since v1.27.0
services:

  davines-db:
    image: mysql:latest
    container_name: davines-db
    volumes:
      - davines-data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: Accursed793110
       MYSQL_DATABASE: davines
    networks:
      - back-end

  davines-ui:
    build: ./frontend
    container_name: davines-ui
    ports:
      - 3000:3000
    networks:
      - front-end

  davines-app:
    build: ./backend
    restart: on-failure
    container_name: davines-app
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Accursed793110
      MYSQL_SERVICE_HOST: davines-db
      MYSQL_URL: jdbc:mysql://davines-db:3306/davines
    ports:
      - 8080:8080
    networks:
      - back-end
      - front-end
    depends_on:
      - davines-db

networks:
  back-end:
    driver: bridge
  front-end:
    driver: bridge

volumes:
  davines-data:




