version: '3' # optional since v1.27.0
services:

  davines-mysql:
    image: mysql:latest
    container_name: davines-mysql
    volumes:
      - davines-data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: Accursed793110
       MYSQL_DATABASE: davines

  davines-app:
    build: ./backend
    container_name: davines-app
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: Accursed793110
    ports:
      - 8080:8080
    depends_on:
      - davines-mysql

  davines-ui:
    build: ./frontend
    container_name: davines-ui
    ports:
      - 3000:3000
    links:
      - davines-app

volumes:
  davines-data:




