describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000')
    cy.get('.nav > :nth-child(4)').click()
    cy.get('#email-login').type('vartand@gmail.com')
    cy.get('#password-login').type('vartan')
    cy.get('.login-button').click()
    cy.wait(1000)
    cy.get('.nav > :nth-child(4)').click()
    cy.get('.menu-items > :nth-child(2)').click()
    cy.get('#update-firstName').clear()
    cy.get('#update-firstName').type('Vartan1')
    cy.get('#update-lastName').clear()
    cy.get('#update-lastName').type('DavtyanTest12')
    cy.get('#update-btn').click()
    cy.wait(1000)
    cy.get('#disabled-firstName').should('have.value', 'Vartan1')
  })
})